GNU nano 4.8                 postgresdb-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: postgresdb-secret
type: Opaque
data:
  postgres-username: cG9zdGdyZXM=
  postgres-password: cGFzc3dvcmQ=